name: Run Tests

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/**

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install modules
        run: npm install

      - name: Lint
        run: npm lint